/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.analysis;

import elip.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTComma(TComma node);
    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTPipe(TPipe node);
    void caseTColon(TColon node);
    void caseTEntry(TEntry node);
    void caseTIf(TIf node);
    void caseTThen(TThen node);
    void caseTElse(TElse node);
    void caseTExclMark(TExclMark node);
    void caseTQuestMark(TQuestMark node);
    void caseTEllipsis(TEllipsis node);
    void caseTEqual(TEqual node);
    void caseTEq(TEq node);
    void caseTNeq(TNeq node);
    void caseTLt(TLt node);
    void caseTGt(TGt node);
    void caseTLCurlyDoubleMinus(TLCurlyDoubleMinus node);
    void caseTRCurlyDoubleMinus(TRCurlyDoubleMinus node);
    void caseTInterger(TInterger node);
    void caseTReal(TReal node);
    void caseTBool(TBool node);
    void caseTTrue(TTrue node);
    void caseTFalse(TFalse node);
    void caseTIdentifier(TIdentifier node);
    void caseTNumber(TNumber node);
    void caseTFracNumber(TFracNumber node);
    void caseTBinNumber(TBinNumber node);
    void caseTBinFracNumber(TBinFracNumber node);
    void caseTCommentLine(TCommentLine node);
    void caseTCommentBlock(TCommentBlock node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
