/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ABinExpAtomic extends PExpAtomic
{
    private TNumberBin _numberBin_;

    public ABinExpAtomic()
    {
        // Constructor
    }

    public ABinExpAtomic(
        @SuppressWarnings("hiding") TNumberBin _numberBin_)
    {
        // Constructor
        setNumberBin(_numberBin_);

    }

    @Override
    public Object clone()
    {
        return new ABinExpAtomic(
            cloneNode(this._numberBin_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABinExpAtomic(this);
    }

    public TNumberBin getNumberBin()
    {
        return this._numberBin_;
    }

    public void setNumberBin(TNumberBin node)
    {
        if(this._numberBin_ != null)
        {
            this._numberBin_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberBin_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberBin_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberBin_ == child)
        {
            this._numberBin_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberBin_ == oldChild)
        {
            setNumberBin((TNumberBin) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
