/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import java.util.*;
import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ABlockExp extends PExp
{
    private final LinkedList<PDeclConst> _declConst_ = new LinkedList<PDeclConst>();
    private PExp _exp_;

    public ABlockExp()
    {
        // Constructor
    }

    public ABlockExp(
        @SuppressWarnings("hiding") List<?> _declConst_,
        @SuppressWarnings("hiding") PExp _exp_)
    {
        // Constructor
        setDeclConst(_declConst_);

        setExp(_exp_);

    }

    @Override
    public Object clone()
    {
        return new ABlockExp(
            cloneList(this._declConst_),
            cloneNode(this._exp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlockExp(this);
    }

    public LinkedList<PDeclConst> getDeclConst()
    {
        return this._declConst_;
    }

    public void setDeclConst(List<?> list)
    {
        for(PDeclConst e : this._declConst_)
        {
            e.parent(null);
        }
        this._declConst_.clear();

        for(Object obj_e : list)
        {
            PDeclConst e = (PDeclConst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declConst_.add(e);
        }
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declConst_)
            + toString(this._exp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declConst_.remove(child))
        {
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDeclConst> i = this._declConst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclConst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
