/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ABoolType extends PType
{
    private TKwBool _kwBool_;

    public ABoolType()
    {
        // Constructor
    }

    public ABoolType(
        @SuppressWarnings("hiding") TKwBool _kwBool_)
    {
        // Constructor
        setKwBool(_kwBool_);

    }

    @Override
    public Object clone()
    {
        return new ABoolType(
            cloneNode(this._kwBool_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABoolType(this);
    }

    public TKwBool getKwBool()
    {
        return this._kwBool_;
    }

    public void setKwBool(TKwBool node)
    {
        if(this._kwBool_ != null)
        {
            this._kwBool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwBool_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwBool_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwBool_ == child)
        {
            this._kwBool_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwBool_ == oldChild)
        {
            setKwBool((TKwBool) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
