/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AExpEquality extends PExpEquality
{
    private PExpRelational _expRelational_;

    public AExpEquality()
    {
        // Constructor
    }

    public AExpEquality(
        @SuppressWarnings("hiding") PExpRelational _expRelational_)
    {
        // Constructor
        setExpRelational(_expRelational_);

    }

    @Override
    public Object clone()
    {
        return new AExpEquality(
            cloneNode(this._expRelational_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpEquality(this);
    }

    public PExpRelational getExpRelational()
    {
        return this._expRelational_;
    }

    public void setExpRelational(PExpRelational node)
    {
        if(this._expRelational_ != null)
        {
            this._expRelational_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRelational_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRelational_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRelational_ == child)
        {
            this._expRelational_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRelational_ == oldChild)
        {
            setExpRelational((PExpRelational) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
