/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AExp extends PExp
{
    private PExpTernary _expTernary_;

    public AExp()
    {
        // Constructor
    }

    public AExp(
        @SuppressWarnings("hiding") PExpTernary _expTernary_)
    {
        // Constructor
        setExpTernary(_expTernary_);

    }

    @Override
    public Object clone()
    {
        return new AExp(
            cloneNode(this._expTernary_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp(this);
    }

    public PExpTernary getExpTernary()
    {
        return this._expTernary_;
    }

    public void setExpTernary(PExpTernary node)
    {
        if(this._expTernary_ != null)
        {
            this._expTernary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTernary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expTernary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expTernary_ == child)
        {
            this._expTernary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expTernary_ == oldChild)
        {
            setExpTernary((PExpTernary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
