/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AExpAdditive extends PExpAdditive
{
    private PExpMultiplicative _expMultiplicative_;

    public AExpAdditive()
    {
        // Constructor
    }

    public AExpAdditive(
        @SuppressWarnings("hiding") PExpMultiplicative _expMultiplicative_)
    {
        // Constructor
        setExpMultiplicative(_expMultiplicative_);

    }

    @Override
    public Object clone()
    {
        return new AExpAdditive(
            cloneNode(this._expMultiplicative_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAdditive(this);
    }

    public PExpMultiplicative getExpMultiplicative()
    {
        return this._expMultiplicative_;
    }

    public void setExpMultiplicative(PExpMultiplicative node)
    {
        if(this._expMultiplicative_ != null)
        {
            this._expMultiplicative_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expMultiplicative_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expMultiplicative_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expMultiplicative_ == child)
        {
            this._expMultiplicative_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expMultiplicative_ == oldChild)
        {
            setExpMultiplicative((PExpMultiplicative) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
