/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AExpMultiplicative extends PExpMultiplicative
{
    private PExpAtomic _expAtomic_;

    public AExpMultiplicative()
    {
        // Constructor
    }

    public AExpMultiplicative(
        @SuppressWarnings("hiding") PExpAtomic _expAtomic_)
    {
        // Constructor
        setExpAtomic(_expAtomic_);

    }

    @Override
    public Object clone()
    {
        return new AExpMultiplicative(
            cloneNode(this._expAtomic_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpMultiplicative(this);
    }

    public PExpAtomic getExpAtomic()
    {
        return this._expAtomic_;
    }

    public void setExpAtomic(PExpAtomic node)
    {
        if(this._expAtomic_ != null)
        {
            this._expAtomic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAtomic_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAtomic_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAtomic_ == child)
        {
            this._expAtomic_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAtomic_ == oldChild)
        {
            setExpAtomic((PExpAtomic) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
