/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AFalseExp extends PExp
{
    private TKwFalse _kwFalse_;

    public AFalseExp()
    {
        // Constructor
    }

    public AFalseExp(
        @SuppressWarnings("hiding") TKwFalse _kwFalse_)
    {
        // Constructor
        setKwFalse(_kwFalse_);

    }

    @Override
    public Object clone()
    {
        return new AFalseExp(
            cloneNode(this._kwFalse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFalseExp(this);
    }

    public TKwFalse getKwFalse()
    {
        return this._kwFalse_;
    }

    public void setKwFalse(TKwFalse node)
    {
        if(this._kwFalse_ != null)
        {
            this._kwFalse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwFalse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwFalse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwFalse_ == child)
        {
            this._kwFalse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwFalse_ == oldChild)
        {
            setKwFalse((TKwFalse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
