/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AFracExpAtomic extends PExpAtomic
{
    private TNumberFrac _numberFrac_;

    public AFracExpAtomic()
    {
        // Constructor
    }

    public AFracExpAtomic(
        @SuppressWarnings("hiding") TNumberFrac _numberFrac_)
    {
        // Constructor
        setNumberFrac(_numberFrac_);

    }

    @Override
    public Object clone()
    {
        return new AFracExpAtomic(
            cloneNode(this._numberFrac_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFracExpAtomic(this);
    }

    public TNumberFrac getNumberFrac()
    {
        return this._numberFrac_;
    }

    public void setNumberFrac(TNumberFrac node)
    {
        if(this._numberFrac_ != null)
        {
            this._numberFrac_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numberFrac_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numberFrac_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numberFrac_ == child)
        {
            this._numberFrac_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numberFrac_ == oldChild)
        {
            setNumberFrac((TNumberFrac) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
