/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AIntType extends PType
{
    private TKwInterger _kwInterger_;

    public AIntType()
    {
        // Constructor
    }

    public AIntType(
        @SuppressWarnings("hiding") TKwInterger _kwInterger_)
    {
        // Constructor
        setKwInterger(_kwInterger_);

    }

    @Override
    public Object clone()
    {
        return new AIntType(
            cloneNode(this._kwInterger_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntType(this);
    }

    public TKwInterger getKwInterger()
    {
        return this._kwInterger_;
    }

    public void setKwInterger(TKwInterger node)
    {
        if(this._kwInterger_ != null)
        {
            this._kwInterger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwInterger_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwInterger_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwInterger_ == child)
        {
            this._kwInterger_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwInterger_ == oldChild)
        {
            setKwInterger((TKwInterger) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
