/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AMultipleListIds extends PListIds
{
    private TIdentifier _id_;
    private TPipe _pipe_;
    private PListIds _ids_;

    public AMultipleListIds()
    {
        // Constructor
    }

    public AMultipleListIds(
        @SuppressWarnings("hiding") TIdentifier _id_,
        @SuppressWarnings("hiding") TPipe _pipe_,
        @SuppressWarnings("hiding") PListIds _ids_)
    {
        // Constructor
        setId(_id_);

        setPipe(_pipe_);

        setIds(_ids_);

    }

    @Override
    public Object clone()
    {
        return new AMultipleListIds(
            cloneNode(this._id_),
            cloneNode(this._pipe_),
            cloneNode(this._ids_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultipleListIds(this);
    }

    public TIdentifier getId()
    {
        return this._id_;
    }

    public void setId(TIdentifier node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPipe getPipe()
    {
        return this._pipe_;
    }

    public void setPipe(TPipe node)
    {
        if(this._pipe_ != null)
        {
            this._pipe_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pipe_ = node;
    }

    public PListIds getIds()
    {
        return this._ids_;
    }

    public void setIds(PListIds node)
    {
        if(this._ids_ != null)
        {
            this._ids_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ids_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._pipe_)
            + toString(this._ids_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._pipe_ == child)
        {
            this._pipe_ = null;
            return;
        }

        if(this._ids_ == child)
        {
            this._ids_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TIdentifier) newChild);
            return;
        }

        if(this._pipe_ == oldChild)
        {
            setPipe((TPipe) newChild);
            return;
        }

        if(this._ids_ == oldChild)
        {
            setIds((PListIds) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
