/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ANegativeExp1 extends PExp1
{
    private TMinus _minus_;
    private PExp0 _exp0_;

    public ANegativeExp1()
    {
        // Constructor
    }

    public ANegativeExp1(
        @SuppressWarnings("hiding") TMinus _minus_,
        @SuppressWarnings("hiding") PExp0 _exp0_)
    {
        // Constructor
        setMinus(_minus_);

        setExp0(_exp0_);

    }

    @Override
    public Object clone()
    {
        return new ANegativeExp1(
            cloneNode(this._minus_),
            cloneNode(this._exp0_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegativeExp1(this);
    }

    public TMinus getMinus()
    {
        return this._minus_;
    }

    public void setMinus(TMinus node)
    {
        if(this._minus_ != null)
        {
            this._minus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minus_ = node;
    }

    public PExp0 getExp0()
    {
        return this._exp0_;
    }

    public void setExp0(PExp0 node)
    {
        if(this._exp0_ != null)
        {
            this._exp0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minus_)
            + toString(this._exp0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minus_ == child)
        {
            this._minus_ = null;
            return;
        }

        if(this._exp0_ == child)
        {
            this._exp0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minus_ == oldChild)
        {
            setMinus((TMinus) newChild);
            return;
        }

        if(this._exp0_ == oldChild)
        {
            setExp0((PExp0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
