/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AOrExp6 extends PExp6
{
    private PExp6 _left_;
    private TKwOr _kwOr_;
    private PExp5 _right_;

    public AOrExp6()
    {
        // Constructor
    }

    public AOrExp6(
        @SuppressWarnings("hiding") PExp6 _left_,
        @SuppressWarnings("hiding") TKwOr _kwOr_,
        @SuppressWarnings("hiding") PExp5 _right_)
    {
        // Constructor
        setLeft(_left_);

        setKwOr(_kwOr_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AOrExp6(
            cloneNode(this._left_),
            cloneNode(this._kwOr_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrExp6(this);
    }

    public PExp6 getLeft()
    {
        return this._left_;
    }

    public void setLeft(PExp6 node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TKwOr getKwOr()
    {
        return this._kwOr_;
    }

    public void setKwOr(TKwOr node)
    {
        if(this._kwOr_ != null)
        {
            this._kwOr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwOr_ = node;
    }

    public PExp5 getRight()
    {
        return this._right_;
    }

    public void setRight(PExp5 node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._kwOr_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._kwOr_ == child)
        {
            this._kwOr_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PExp6) newChild);
            return;
        }

        if(this._kwOr_ == oldChild)
        {
            setKwOr((TKwOr) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PExp5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
