/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import java.util.*;
import elipses.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PDeclFunc> _declFunc_ = new LinkedList<PDeclFunc>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _declFunc_)
    {
        // Constructor
        setDeclFunc(_declFunc_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._declFunc_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PDeclFunc> getDeclFunc()
    {
        return this._declFunc_;
    }

    public void setDeclFunc(List<?> list)
    {
        for(PDeclFunc e : this._declFunc_)
        {
            e.parent(null);
        }
        this._declFunc_.clear();

        for(Object obj_e : list)
        {
            PDeclFunc e = (PDeclFunc) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._declFunc_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declFunc_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declFunc_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PDeclFunc> i = this._declFunc_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PDeclFunc) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
