/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ARealType extends PType
{
    private TKwReal _kwReal_;

    public ARealType()
    {
        // Constructor
    }

    public ARealType(
        @SuppressWarnings("hiding") TKwReal _kwReal_)
    {
        // Constructor
        setKwReal(_kwReal_);

    }

    @Override
    public Object clone()
    {
        return new ARealType(
            cloneNode(this._kwReal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealType(this);
    }

    public TKwReal getKwReal()
    {
        return this._kwReal_;
    }

    public void setKwReal(TKwReal node)
    {
        if(this._kwReal_ != null)
        {
            this._kwReal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kwReal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kwReal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kwReal_ == child)
        {
            this._kwReal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kwReal_ == oldChild)
        {
            setKwReal((TKwReal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
