/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ASignatureParams extends PSignatureParams
{

    public ASignatureParams()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ASignatureParams();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASignatureParams(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
