/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class ASingleSignatureParams extends PSignatureParams
{
    private PSignatureParam _signatureParam_;

    public ASingleSignatureParams()
    {
        // Constructor
    }

    public ASingleSignatureParams(
        @SuppressWarnings("hiding") PSignatureParam _signatureParam_)
    {
        // Constructor
        setSignatureParam(_signatureParam_);

    }

    @Override
    public Object clone()
    {
        return new ASingleSignatureParams(
            cloneNode(this._signatureParam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleSignatureParams(this);
    }

    public PSignatureParam getSignatureParam()
    {
        return this._signatureParam_;
    }

    public void setSignatureParam(PSignatureParam node)
    {
        if(this._signatureParam_ != null)
        {
            this._signatureParam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._signatureParam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._signatureParam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._signatureParam_ == child)
        {
            this._signatureParam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._signatureParam_ == oldChild)
        {
            setSignatureParam((PSignatureParam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
