/* This file was generated by SableCC (http://www.sablecc.org/). */

package Elipses.node;

import Elipses.analysis.*;

@SuppressWarnings("nls")
public final class TKwAnd extends Token
{
    public TKwAnd()
    {
        super.setText("e");
    }

    public TKwAnd(int line, int pos)
    {
        super.setText("e");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwAnd(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwAnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwAnd text.");
    }
}
