/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class TKwInteger extends Token
{
    public TKwInteger()
    {
        super.setText("inteiro");
    }

    public TKwInteger(int line, int pos)
    {
        super.setText("inteiro");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwInteger(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwInteger(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwInteger text.");
    }
}
