/* This file was generated by SableCC (http://www.sablecc.org/). */

package Elipses.node;

import Elipses.analysis.*;

@SuppressWarnings("nls")
public final class TKwOr extends Token
{
    public TKwOr()
    {
        super.setText("ou");
    }

    public TKwOr(int line, int pos)
    {
        super.setText("ou");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwOr(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwOr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwOr text.");
    }
}
