/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.node;

import elipses.analysis.*;

@SuppressWarnings("nls")
public final class TKwTrue extends Token
{
    public TKwTrue()
    {
        super.setText("verdadeiro");
    }

    public TKwTrue(int line, int pos)
    {
        super.setText("verdadeiro");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwTrue(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwTrue(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwTrue text.");
    }
}
