/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.node;

import elip.analysis.*;

@SuppressWarnings("nls")
public final class TEllipsis extends Token
{
    public TEllipsis()
    {
        super.setText("...");
    }

    public TEllipsis(int line, int pos)
    {
        super.setText("...");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEllipsis(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEllipsis(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEllipsis text.");
    }
}
