/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.node;

import elip.analysis.*;

@SuppressWarnings("nls")
public final class TEntry extends Token
{
    public TEntry()
    {
        super.setText("entrada");
    }

    public TEntry(int line, int pos)
    {
        super.setText("entrada");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEntry(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntry(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEntry text.");
    }
}
