/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.node;

import elip.analysis.*;

@SuppressWarnings("nls")
public final class TLCurlyDoubleMinus extends Token
{
    public TLCurlyDoubleMinus()
    {
        super.setText("{--");
    }

    public TLCurlyDoubleMinus(int line, int pos)
    {
        super.setText("{--");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLCurlyDoubleMinus(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLCurlyDoubleMinus(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLCurlyDoubleMinus text.");
    }
}
