/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.node;

import elip.analysis.*;

@SuppressWarnings("nls")
public final class TQuestMark extends Token
{
    public TQuestMark()
    {
        super.setText("?");
    }

    public TQuestMark(int line, int pos)
    {
        super.setText("?");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TQuestMark(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTQuestMark(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TQuestMark text.");
    }
}
