/* This file was generated by SableCC (http://www.sablecc.org/). */

package elip.node;

import elip.analysis.*;

@SuppressWarnings("nls")
public final class TRCurlyDoubleMinus extends Token
{
    public TRCurlyDoubleMinus()
    {
        super.setText("--}");
    }

    public TRCurlyDoubleMinus(int line, int pos)
    {
        super.setText("--}");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRCurlyDoubleMinus(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRCurlyDoubleMinus(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRCurlyDoubleMinus text.");
    }
}
