/* This file was generated by SableCC (http://www.sablecc.org/). */

package calculadora.analysis;

import calculadora.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAExp(AExp node);
    void caseAFatorExpr(AFatorExpr node);
    void caseASomaExpr(ASomaExpr node);
    void caseAMenosExpr(AMenosExpr node);
    void caseATermoFator(ATermoFator node);
    void caseAMultFator(AMultFator node);
    void caseADivFator(ADivFator node);
    void caseAModFator(AModFator node);
    void caseANumeroTermo(ANumeroTermo node);
    void caseAParTermo(AParTermo node);

    void caseTNumero(TNumero node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
