/* This file was generated by SableCC (http://www.sablecc.org/). */

package elipses.parser;

import elipses.node.*;
import elipses.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTKwConst(@SuppressWarnings("unused") TKwConst node)
    {
        this.index = 0;
    }

    @Override
    public void caseTKwInterger(@SuppressWarnings("unused") TKwInterger node)
    {
        this.index = 1;
    }

    @Override
    public void caseTKwReal(@SuppressWarnings("unused") TKwReal node)
    {
        this.index = 2;
    }

    @Override
    public void caseTKwBool(@SuppressWarnings("unused") TKwBool node)
    {
        this.index = 3;
    }

    @Override
    public void caseTKwTrue(@SuppressWarnings("unused") TKwTrue node)
    {
        this.index = 4;
    }

    @Override
    public void caseTKwFalse(@SuppressWarnings("unused") TKwFalse node)
    {
        this.index = 5;
    }

    @Override
    public void caseTKwEntry(@SuppressWarnings("unused") TKwEntry node)
    {
        this.index = 6;
    }

    @Override
    public void caseTKwIf(@SuppressWarnings("unused") TKwIf node)
    {
        this.index = 7;
    }

    @Override
    public void caseTKwThen(@SuppressWarnings("unused") TKwThen node)
    {
        this.index = 8;
    }

    @Override
    public void caseTKwElse(@SuppressWarnings("unused") TKwElse node)
    {
        this.index = 9;
    }

    @Override
    public void caseTKwAnd(@SuppressWarnings("unused") TKwAnd node)
    {
        this.index = 10;
    }

    @Override
    public void caseTKwNot(@SuppressWarnings("unused") TKwNot node)
    {
        this.index = 11;
    }

    @Override
    public void caseTKwOr(@SuppressWarnings("unused") TKwOr node)
    {
        this.index = 12;
    }

    @Override
    public void caseTKwLambda(@SuppressWarnings("unused") TKwLambda node)
    {
        this.index = 13;
    }

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 14;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 15;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 16;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 17;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 18;
    }

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 19;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 20;
    }

    @Override
    public void caseTLBrack(@SuppressWarnings("unused") TLBrack node)
    {
        this.index = 21;
    }

    @Override
    public void caseTRBrack(@SuppressWarnings("unused") TRBrack node)
    {
        this.index = 22;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 23;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 24;
    }

    @Override
    public void caseTEq(@SuppressWarnings("unused") TEq node)
    {
        this.index = 25;
    }

    @Override
    public void caseTLt(@SuppressWarnings("unused") TLt node)
    {
        this.index = 26;
    }

    @Override
    public void caseTGt(@SuppressWarnings("unused") TGt node)
    {
        this.index = 27;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 28;
    }

    @Override
    public void caseTNumberInt(@SuppressWarnings("unused") TNumberInt node)
    {
        this.index = 29;
    }

    @Override
    public void caseTNumberFrac(@SuppressWarnings("unused") TNumberFrac node)
    {
        this.index = 30;
    }

    @Override
    public void caseTNumberBin(@SuppressWarnings("unused") TNumberBin node)
    {
        this.index = 31;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 32;
    }
}
